version: '3.4'
services:
  #F1
  figaro:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    volumes:
      - ./indexF1.html:/usr/share/nginx/html/index.html

    expose:
      - "80"
    networks:
      - traefik
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.backend=figaro"
      - "traefik.frontend.rule=Host:figaro.localhost"
      - "traefik.port=80"

  
    #Gorafi
  gorafi:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    volumes:
      - ./../Gorafi/indexG1.html:/usr/share/nginx/html/index.html

    expose:
      - "80"
    networks:
      - traefik
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.backend=gorafi"
      - "traefik.frontend.rule=Host:gorafi.localhost"
      - "traefik.port=80"

#Docker Networks
networks:


  traefik:
    external: 
      name: traefik_webgateway